# Generated by Django 4.2 on 2023-07-11 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='profile/')),
                ('title', models.CharField(max_length=25)),
                ('title2', models.CharField(max_length=25)),
                ('facebook', models.URLField(max_length=30)),
                ('github', models.URLField(max_length=30)),
                ('twitter', models.URLField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('cv', models.FileField(upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
