# Generated by Django 4.2 on 2023-07-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_info_dribble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='dribble',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='facebook',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='github',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='twitter',
            field=models.CharField(max_length=30),
        ),
    ]
