# Generated by Django 4.2 on 2023-07-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='project_title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
