# Generated by Django 4.2 on 2023-07-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
