# Generated by Django 4.2 on 2023-07-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_client_company_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='projects/')),
                ('project_link', models.CharField(max_length=70)),
                ('project_desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
