# Generated by Django 4.2 on 2023-07-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='author_title',
            new_name='author_company',
        ),
    ]
