# Generated by Django 4.2 on 2023-07-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_author_title_testimonial_author_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20)),
                ('year', models.IntegerField(max_length=5)),
                ('designer_name', models.CharField(max_length=20)),
                ('designer_profile_link', models.CharField(max_length=50)),
            ],
        ),
    ]
